#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Export the requirement baseline to reader-friendly formats.

Usage: python tools/export.py [--root PATH] [--out DIR]

Writes to build/ (by default):
  requirements.csv   one row per requirement, UTF-8 with BOM (opens directly in spreadsheet
                     tools and imports into tender platforms)
  catalogue.md       all requirements grouped by set and area
  traceability.md    SOL -> PROC / IMPL / use-case matrix
  scoring.md         procurement evaluation sheet with effective weights

Refuses to export when the lint reports errors, so exported files always describe a
consistent baseline.
"""
import argparse, csv, pathlib, sys
from lint import DEFAULT_ROOT, lint

SETS = ("SOL", "PROC", "IMPL")
CSV_FIELDS = ["id", "set", "area", "title", "priority", "type", "level", "layer", "statement",
              "acceptance_criteria", "verification", "allocated_to", "satisfies", "parents",
              "use_cases", "standards", "procurement_kind", "evidence_required", "max_points",
              "weight_in_area", "effective_weight", "status", "owner"]


def md_cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def rows(res):
    area_weights = {a: (v or {}).get("weight", 0) for a, v in res.vocab["areas"].items()}
    order = {s: i for i, s in enumerate(SETS)}
    areas = list(res.vocab["areas"])
    for rid, (_, r, s) in sorted(res.records.items(),
                                 key=lambda kv: (order[kv[1][2]], areas.index(kv[0].split("-")[1]), kv[0])):
        tr = r.get("traces") or {}
        proc = r.get("procurement") or {}
        scoring = proc.get("scoring") or {}
        area = rid.split("-")[1]
        weight = scoring.get("weight")
        yield {
            "id": rid, "set": s, "area": area, "title": r["title"], "priority": r["priority"],
            "type": r["type"], "level": r["level"], "layer": r["layer"],
            "statement": r["statement"],
            "acceptance_criteria": "\n".join(f"- {c}" for c in r["acceptance_criteria"]),
            "verification": r["verification"], "allocated_to": ", ".join(r["allocated_to"]),
            "satisfies": ", ".join(tr.get("satisfies", [])),
            "parents": ", ".join(tr.get("parents", [])),
            "use_cases": ", ".join(tr.get("use_cases", [])),
            "standards": ", ".join(tr.get("standards", [])),
            "procurement_kind": proc.get("kind", ""),
            "evidence_required": "\n".join(f"- {e}" for e in proc.get("evidence_required", [])),
            "max_points": scoring.get("max_points", ""),
            "weight_in_area": "" if weight is None else weight,
            "effective_weight": "" if weight is None else round(weight * area_weights.get(area, 0), 4),
            "status": r["status"], "owner": r["owner"],
        }


def write_csv(path, data):
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        w.writeheader()
        w.writerows(data)


def write_catalogue(path, data, res, version):
    out = [f"# Requirement catalogue — baseline {version}", "",
           "Generated by `tools/export.py` from `requirements/`. Do not edit by hand.", ""]
    for s in SETS:
        out += [f"## {s} — {res.vocab['sets'][s]['name']}", ""]
        area = None
        for row in (d for d in data if d["set"] == s):
            if row["area"] != area:
                area = row["area"]
                out += [f"### {area} — {res.vocab['areas'][area]['name']}", ""]
            out += [f"#### {row['id']} {row['title']}", "",
                    f"**{row['priority']}** · {row['type']} · {row['level']} · {row['layer']} · "
                    f"verification: {row['verification']} · status: {row['status']} · owner: {row['owner']}", "",
                    f"> {row['statement']}", "", "Acceptance criteria:", "", row["acceptance_criteria"], ""]
            if row["satisfies"]:
                out += [f"Satisfies: {row['satisfies']}", ""]
            if row["procurement_kind"]:
                line = f"Procurement: {row['procurement_kind']}"
                if row["max_points"] != "":
                    line += f", max {row['max_points']} points, weight in area {row['weight_in_area']}"
                out += [line, "", "Evidence required:", "", row["evidence_required"], ""]
    path.write_text("\n".join(out))


def write_traceability(path, data, version):
    sol = [d for d in data if d["set"] == "SOL"]
    by_sol = {d["id"]: {"PROC": [], "IMPL": []} for d in sol}
    for d in data:
        for t in filter(None, d["satisfies"].split(", ")):
            by_sol[t][d["set"]].append(d["id"])
    out = [f"# Traceability matrix — baseline {version}", "",
           "Generated by `tools/export.py`. Goals (area GOAL) are realised through their children, so they "
           "have no PROC or IMPL records; for other rows a dash under PROC or IMPL is a coverage gap (lint W01 / W03).", "",
           "| SOL | Priority | Title | Parents | PROC | IMPL | Use cases |", "|---|---|---|---|---|---|---|"]
    for d in sol:
        t = by_sol[d["id"]]
        out.append(f"| {d['id']} | {d['priority']} | {md_cell(d['title'])} | {d['parents'] or '—'} | {', '.join(t['PROC']) or '—'} | "
                   f"{', '.join(t['IMPL']) or '—'} | {d['use_cases'] or '—'} |")
    path.write_text("\n".join(out) + "\n")


def write_scoring(path, data, res, version):
    out = [f"# Procurement evaluation sheet — baseline {version}", "",
           "Generated by `tools/export.py`. Effective weight = area weight (schema/vocab.yaml) × "
           "weight in area. Offer score = Σ (points awarded / max points) × effective weight. "
           "Pass/fail records reject an offer that does not meet them.", ""]
    out += ["## Pass/fail (mandatory and qualification)", "",
            "| ID | Kind | Title | Satisfies |", "|---|---|---|---|"]
    out += [f"| {d['id']} | {d['procurement_kind']} | {md_cell(d['title'])} | {d['satisfies']} |"
            for d in data if d["set"] == "PROC" and d["procurement_kind"] in ("mandatory", "qualification")]
    out += ["", "## Scored", "",
            "| ID | Area | Area weight | Title | Max points | Weight in area | Effective weight |",
            "|---|---|---|---|---|---|---|"]
    total = 0
    for d in data:
        if d["set"] == "PROC" and d["max_points"] != "":
            aw = res.vocab["areas"][d["area"]].get("weight", 0)
            total += d["effective_weight"]
            out.append(f"| {d['id']} | {d['area']} | {aw} | {md_cell(d['title'])} | {d['max_points']} | "
                       f"{d['weight_in_area']} | {d['effective_weight']} |")
    out += ["", f"Sum of effective weights: {round(total, 4)} (1.0 when every weighted area has scored records).", ""]
    path.write_text("\n".join(out))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", type=pathlib.Path, default=DEFAULT_ROOT, help="repository root")
    ap.add_argument("--out", type=pathlib.Path, default=None, help="output directory (default: <root>/build)")
    args = ap.parse_args(argv)
    res = lint(args.root)
    if res.errors:
        print("lint reports errors; run tools/lint.py and fix them before exporting", file=sys.stderr)
        return 1
    out = args.out or args.root / "build"
    out.mkdir(parents=True, exist_ok=True)
    version = (args.root / "VERSION").read_text().strip() if (args.root / "VERSION").exists() else "unversioned"
    data = list(rows(res))
    write_csv(out / "requirements.csv", data)
    write_catalogue(out / "catalogue.md", data, res, version)
    write_traceability(out / "traceability.md", data, version)
    write_scoring(out / "scoring.md", data, res, version)
    print(f"exported {len(data)} requirements to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
